<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>Lana</RootNamespace>
    <AssemblyName>Lana</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationIcon>Assets/lana.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Themes\AppTheme.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="IoTClient" Version="1.0.40" />
    <PackageReference Include="LibVLCSharp" Version="3.9.7" />
    <PackageReference Include="LibVLCSharp.Avalonia" Version="3.9.7" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
    <PackageReference Include="MQTTnet" Version="4.3.3.952" />
    <PackageReference Include="System.IO.Ports" Version="9.0.4" />
    <PackageReference Include="ToolGood.Words.Pinyin" Version="3.1.0.4" />
    <PackageReference Include="VideoLAN.LibVLC.Mac" Version="3.1.2" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Licenses\**\*" CopyToOutputDirectory="PreserveNewest" Link="Licenses\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
